[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/sortition-sum-game",
    "traits/sortition-sum-game-link",
    "traits/schelling-game-shared-link",
    "pallets/election",
    "pallets/project-submission",
    "pallets/schelling-game-shared",
    "pallets/profile-validation",
    "pallets/tags",
    "pallets/spaces",
    "runtime",
]
[profile.release]
panic = "unwind"
