[workspace]
members = [
    "node",
    "pallets/template",
    "pallets/schelling-game",
    "traits/schelling-game-link",
    "pallets/election",
    "runtime",
]
[profile.release]
panic = "unwind"
